### ISSUE TITLE
useEffect startRecording makes recordingTime jump/skip

### ISSUE THREAD

**Issue by philmetzger** [samhirtarif/react-audio-recorder#109]
When I startRecording in a useEffect on mount, then the recording time jumps a lot, sometimes skips 2 seconds etc.

```
useEffect(() => {
    startRecording();

    return () => startRecording();
  }, []);
```

Anyone know how to fix this?

**Comment by samhirtarif** [comment]
@philmetzger 

```ts
useEffect(() => {
    startRecording();

    return () => stopRecording();
}, []);
```

I believe the usage of `startRecording` in the clean up method of the `useEffect` may be a typo and you probably intended to use `stopRecording`? That might be the source of the problem, especially if you are testing on the dev environment with `Strict` mode, since strict mode runs each `useEffect` twice (the code you've shared would result in `startRecording` being called 3 times.

**Comment by philmetzger** [comment]
ah interesting about the strict mode, thats probably it.

Yep disabled strict mode and all is well. thanks for the heads up, didnt think about that! gotta remember that going forward :)
