### ISSUE TITLE
Change the color of icons

### ISSUE THREAD

**Issue by Vee339** [samhirtarif/react-audio-recorder#19]
Hi, I hope you are doing well.

I am using this and it's just incredible. However, I am trying to change the color of the icons(of the pause button and play button). If it is possible to do, please tell me.

**Comment by samhirtarif** [comment]
Hey @Vee339
I am off for vacations and will be returning on Monday. I'll look into this then.

**Comment by samhirtarif** [comment]
@Vee339 I've added an example [here](https://stackblitz.com/edit/react-ts-guryi5?file=App.tsx,style.css%3AL6,index.tsx) of how you can change the colors for the icons.
In order to generate the filter you can use this [codepen](https://codepen.io/sosuke/pen/Pjoqqp), just add the target color and copy the generated filter.

The reason you will need to use filters is because the icons are SVGs and in my experience the only way to change color for an svg icon is applying a filter on it.

**Comment by Vee339** [comment]
@samhirtarif Thank you so much for your help. 
I have successfully changed the colors of icons by applying the filter property.

**Comment by samhirtarif** [comment]
Glad to be of help!
Would really appreciate if you starred ⭐ the repo 😄

**Comment by Vee339** [comment]
👍

**Comment by jokerf6** [comment]
discard donot work successfully

**Comment by samhirtarif** [comment]
@jokerf6 What do you mean when you are referring to discard?

**Comment by Meetpidev** [comment]
can we change the icons ?
